name: talk-booking

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:19.03.0-dind

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Set Docker buildx
      run: docker buildx create --use

    - name: Log in to Docker Registry
      run: docker login -u ${{ secrets.CI_REGISTRY_USER }} -p ${{ secrets.CI_REGISTRY_PASSWORD }} ${{ secrets.CI_REGISTRY }}

    - name: Build Docker image
      run: docker build -t ${{ secrets.CI_REGISTRY }}/talk-booking:cicd-python3.11 .
      working-directory: /services/talk_booking

    - name: Push Docker image
      run: docker push ${{ secrets.CI_REGISTRY }}/talk-booking:cicd-python3.11
      working-directory: /services/talk_booking

    - name: Run Tests
      run: docker run -it ${{ secrets.CI_REGISTRY }}/talk-booking:cicd-python3.11 pytest /services/talk_booking/ci-cd.yml
      working-directory: /services/talk_booking